### ISSUE TITLE
Evaluate Optimism-Kovan contract support

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-deployments#20]
- [x] Define checklist in internal wiki
- [x] Deploy contracts
- [x] Execute on checklist and post results

**Comment by jpalvarezl** [comment]
Question: are the contracts already deployed? It appears that the `chainId` for Optimism-Kovan is `69` which doesn't appear to have been merged to the this repo yet.

**Comment by jpalvarezl** [comment]
Just to document the completion of point 1 of this task: the [link](https://app.gitbook.com/o/-MhyDtGxUyODu7d4sgda/s/-MhyEL1Pq_BGR0rFugaE/backend/contract-deployment-checks) to the checklist.

**Comment by jpalvarezl** [comment]
Bridge between Kovan and Optimism-Kovan: https://gateway.optimism.io/deposit
