### ISSUE TITLE
Evaluate `Aurora Testnet` Chain

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-deployments#30]
RPC: https://testnet.aurora.dev/

- [x] If contracts are not deployed. Deploy them using [the tool](https://github.com/gnosis/safe-contracts)
  - [x] Verify the chain at https://chainlist.org/ . Please fill the Chain ID: **1313161555**
- [x] Please document links of interest such as faucets, bridges, block explorer, etc. as comments in this issue.
- [x] Execute the steps in our internal [guide](https://app.gitbook.com/o/-MhyDtGxUyODu7d4sgda/s/-MhyEL1Pq_BGR0rFugaE/backend/contract-deployment-checks) for user side validation of the contracts:
  - [x] Deploy 2 L2 safes
    - https://explorer.testnet.aurora.dev/address/0x0cF5845fC201dd30A01D42C857a81f9aF2682866/transactions
    - https://explorer.testnet.aurora.dev/address/0x47C9b72A1e0a011AFdcE280Dc5891e0b405805e8/transactions 
  - [x] Transfer native currency of the chain to one of the safes from your EOA
    - https://explorer.testnet.aurora.dev/address/0x0cF5845fC201dd30A01D42C857a81f9aF2682866/transactions
  - [x] Transfer ERC20 token (please provide link and/or deploy one if necessary) to one of the safes
    - Deployed asset [link](https://explorer.testnet.aurora.dev/address/0xE560A1404f29f243374053BF2A3618A75C5F3590/transactions) 
  - [x] Transfer ERC20 token and native coin between the safes
    - `0x1de7253aad26d6f670876088443ed2cdadf20964e4c61617d7ce2e5082a8081d` tx hash for aETH transfer between.  safes.
    -  Verified with @rmeissner 's event based indexer tool
  - [x] Add an additional owner to one of the safes
    - Transaction hash: `0xcb905e8b19109c69c6c4a4073a687f0758c0c6265763864434be93246f55b49b` 
    - Verified with `safe-tasks`
  
Where possible, provide links to the transactions in the block explorer of the chain.

**Comment by jpalvarezl** [comment]
Link to bridge: https://testnet.rainbowbridge.app/transfer
