### ISSUE TITLE
Evaluate `Aurora` Chain

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-deployments#31]
RPC: https://mainnet.aurora.dev

- [x] If contracts are not deployed. Deploy them using [the tool](https://github.com/gnosis/safe-contracts)
  - [x] Verify the chain at https://chainlist.org/ . Please fill the Chain ID: **1313161554**
- [x] Please document links of interest such as faucets, bridges, block explorer, etc. as comments in this issue.
- [x] Execute the steps in our internal [guide](https://app.gitbook.com/o/-MhyDtGxUyODu7d4sgda/s/-MhyEL1Pq_BGR0rFugaE/backend/contract-deployment-checks) for user side validation of the contracts:
  - [x] Deploy 2 L2 safes
    - https://explorer.mainnet.aurora.dev/address/0xBc089147F86Bcc1341D9F2870997920082A7b0BA/transactions
    - https://explorer.mainnet.aurora.dev/address/0x662C65d4E1332d0d08158C4e240d8d72d5FE8672/transactions
  - [x] Transfer native currency of the chain to one of the safes from your EOA
  - [x] Transfer ERC20 token (please provide link and/or deploy one if necessary) to one of the safes
  - [x] Transfer ERC20 token and native coin between the safes
    - ERC20 transfer: https://explorer.mainnet.aurora.dev/tx/0x7cbdff6ed59af8dd7c6a0d3ccfa6e2e6cec6e9ed260249271e1c1ab5ce5944fe/token-transfers  
  - [x] Add an additional owner to one of the safes
  
Where possible, provide links to the transactions in the block explorer of the chain.

**Comment by jpalvarezl** [comment]
Note: We cannot close the issue until we are able to verify that events are emited correctly
