### ISSUE TITLE
hi from gitcoin - need a polygon address for v1.1.1 (chain 137)

### ISSUE THREAD

**Issue by owocki** [gnosis/safe-deployments#47]
hi from gitcoin,

we are working off of [this guide](https://www.loom.com/share/ca34aabcd62747fb9fb89bd463b4c741) to claim funds from multisig.gitcoindao.eth on polygon.

this multisig is a 1.1.1 multisig.    and polygon chain is chain 137.

i dont see a corresponding address in https://github.com/gnosis/safe-deployments/blob/main/src/assets/v1.1.1/proxy_factory.json for chain id 137.  is there any way to get one deployed?

**Comment by owocki** [comment]
is this it? https://polygonscan.com/address/0x76e2cfc1f5fa8f6a5b3fc4c8f4788f0116861f9b

its just not in the blob?

**Comment by owocki** [comment]
(copying my question from https://discord.com/channels/477106835862716416/763757827701211137/923269651100758036 here )

what can i do to deploy a safe at address 0xde21f729137c5af1b01d73af1dc21effa2b8a0d6 on polygon, and claim the $15k in funds there?

i'm following the guide here ( https://www.loom.com/share/ca34aabcd62747fb9fb89bd463b4c741 ) about how to deploy this safe on polygon, and was able to generate a safe via txn https://polygonscan.com/tx/0x39b51d747f9cd7815c62fa9417264f809d9ffad084ad3ebadedfc818fa3191be on polygon, but the address of the generated safe is address ( 0x4f3000b30193baff8a4b80eba191139a63e2cc88 ) - not the same as the address generated on the mainnet ( 0xde21f729137c5af1b01d73af1dc21effa2b8a0d6 ).

one thing i was thinking about doing was incrementing the nonce on my deployed address ( 0x00de4b13153673bcae2616b67bf822500d325fc3 ) on polygon, which is currently 15, to 4062 (which was the nonce on my original mainnet deploy tx).  would that work?  or is the nonce of the deployer account non-material and its the proxy that matters?

thanks in advance.

**Comment by owocki** [comment]
stack exchange question: https://ethereum.stackexchange.com/questions/117109/how-to-withdraw-l2-funds-from-polygon

**Comment by rmeissner** [comment]
The factory should be present and can be used but for your case it you cannot follow the video. I will comment on stackexchange.
