### ISSUE TITLE
Add proxy factory 1.1.1 on BSC to the list

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe-deployments#52]
https://bscscan.com/address/0x76E2cFc1F5Fa8F6a5b3fC4c8F4788F0116861F9B

**Comment by rmeissner** [comment]
There is no code at this address

**Comment by mikheevm** [comment]
Lol etherscan labeling mislead me

**Comment by mikheevm** [comment]
Does it make sense to deploy it there to allow users to recover lost funds? I know we didn't support BSC in 1.1.1, but there have been a few cases where people sent funds to their mainnet 1.1.1 safe on BSC
